/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'mdi:information-outline',
      order: 99
    },
    children: [
      {
        name: 'about_help',
        path: '/about/help',
        component: 'view.about_help',
        meta: {
          title: 'about_help',
          i18nKey: 'route.about_help',
          icon: 'mdi:help-circle-outline',
          order: 2
        }
      },
      {
        name: 'about_version',
        path: '/about/version',
        component: 'view.about_version',
        meta: {
          title: 'about_version',
          i18nKey: 'route.about_version',
          icon: 'mdi:information-outline',
          order: 1
        }
      }
    ]
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base',
    meta: {
      title: 'audit',
      icon: 'ph:warning-bold',
      i18nKey: 'route.audit',
      order: 4
    },
    children: [
      {
        name: 'audit_baselogs',
        path: '/audit/baselogs',
        component: 'view.audit_baselogs',
        meta: {
          title: 'audit_baselogs',
          i18nKey: 'route.audit_baselogs',
          icon: 'hugeicons:files-01',
          roles: ['R_SUPER']
        }
      },
      {
        name: 'audit_filetransferlogs',
        path: '/audit/filetransferlogs',
        component: 'view.audit_filetransferlogs',
        meta: {
          title: 'audit_filetransferlogs',
          i18nKey: 'route.audit_filetransferlogs',
          icon: 'solar:square-transfer-horizontal-linear',
          roles: ['R_SUPER']
        }
      },
      {
        name: 'audit_loginlogs',
        path: '/audit/loginlogs',
        component: 'view.audit_loginlogs',
        meta: {
          title: 'audit_loginlogs',
          i18nKey: 'route.audit_loginlogs',
          icon: 'ic:baseline-login'
        }
      },
      {
        name: 'audit_error-logs',
        path: '/audit/error-logs',
        component: 'view.audit_error-logs',
        meta: {
          title: 'audit_error-logs',
          i18nKey: 'route.audit_error-logs',
          icon: 'mdi:alert-circle-outline',
          roles: ['R_SUPER']
        }
      }
    ]
  },
  {
    name: 'devices',
    path: '/devices',
    component: 'layout.base$view.devices',
    meta: {
      title: 'devices',
      i18nKey: 'route.devices',
      icon: 'mdi:desktop-classic',
      order: 6
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'my-devices',
    path: '/my-devices',
    component: 'layout.base',
    meta: {
      title: 'my-devices',
      i18nKey: 'route.my-devices',
      icon: 'mdi:book-open-variant',
      order: 3
    },
    children: [
      {
        name: 'my-devices_manage',
        path: '/my-devices/manage',
        component: 'view.my-devices_manage',
        meta: {
          title: 'my-devices_manage',
          i18nKey: 'route.my-devices_manage',
          icon: 'mdi:book-cog',
          order: 3
        }
      },
      {
        name: 'my-devices_peers',
        path: '/my-devices/peers',
        component: 'view.my-devices_peers',
        meta: {
          title: 'my-devices_peers',
          i18nKey: 'route.my-devices_peers',
          icon: 'mdi:account-multiple',
          order: 1
        }
      },
      {
        name: 'my-devices_tags',
        path: '/my-devices/tags',
        component: 'view.my-devices_tags',
        meta: {
          title: 'my-devices_tags',
          i18nKey: 'route.my-devices_tags',
          icon: 'mdi:tag-multiple',
          order: 2
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'hugeicons:system-update-01',
      order: 5
    },
    children: [
      {
        name: 'system_mail',
        path: '/system/mail',
        meta: {
          title: 'system_mail',
          i18nKey: 'route.system_mail',
          roles: ['R_SUPER']
        },
        children: [
          {
            name: 'system_mail_logs',
            path: '/system/mail/logs',
            component: 'view.system_mail_logs',
            meta: {
              title: 'system_mail_logs',
              i18nKey: 'route.system_mail_logs',
              icon: 'icon-park-outline:upload-logs',
              roles: ['R_SUPER']
            }
          },
          {
            name: 'system_mail_template',
            path: '/system/mail/template',
            component: 'view.system_mail_template',
            meta: {
              title: 'system_mail_template',
              i18nKey: 'route.system_mail_template',
              icon: 'fluent:mail-template-16-regular',
              roles: ['R_SUPER']
            }
          }
        ]
      },
      {
        name: 'system_oauth',
        path: '/system/oauth',
        component: 'view.system_oauth',
        meta: {
          title: 'system_oauth',
          i18nKey: 'route.system_oauth',
          icon: 'mdi:shield-lock',
          roles: ['R_SUPER']
        }
      },
      {
        name: 'system_server',
        path: '/system/server',
        component: 'view.system_server',
        meta: {
          title: 'system_server',
          i18nKey: 'route.system_server',
          icon: 'mdi:server-network'
        }
      },
      {
        name: 'system_tokens',
        path: '/system/tokens',
        component: 'view.system_tokens',
        meta: {
          title: 'system_tokens',
          i18nKey: 'route.system_tokens',
          icon: 'mdi:key-*variant',
          roles: ['R_SUPER']
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      icon: 'majesticons:users-line',
      i18nKey: 'route.user',
      order: 2
    },
    children: [
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: 'user_list',
          i18nKey: 'route.user_list',
          requiresAuth: true,
          icon: 'gravity-ui:person',
          roles: ['R_SUPER']
        }
      },
      {
        name: 'user_profile',
        path: '/user/profile',
        component: 'view.user_profile',
        meta: {
          title: 'user_profile',
          i18nKey: 'route.user_profile',
          requiresAuth: true,
          icon: 'mdi:card-account-details-outline',
          order: 1,
          roles: ['R_USER']
        }
      },
      {
        name: 'user_sessions',
        path: '/user/sessions',
        component: 'view.user_sessions',
        meta: {
          title: 'user_sessions',
          i18nKey: 'route.user_sessions',
          requiresAuth: true,
          icon: 'carbon:mobile-session',
          roles: ['R_SUPER']
        }
      }
    ]
  },
  {
    name: 'workspace',
    path: '/workspace',
    component: 'layout.base',
    meta: {
      title: 'workspace',
      i18nKey: 'route.workspace',
      roles: ['R_USER'],
      hideInMenu: true,
      icon: 'mdi:account-circle',
      order: 2
    },
    children: [
      {
        name: 'workspace_devices',
        path: '/workspace/devices',
        component: 'view.workspace_devices',
        meta: {
          title: 'workspace_devices',
          i18nKey: 'route.workspace_devices',
          roles: ['R_USER'],
          hideInMenu: true,
          icon: 'mdi:monitor-multiple',
          order: 2
        }
      },
      {
        name: 'workspace_overview',
        path: '/workspace/overview',
        component: 'view.workspace_overview',
        meta: {
          title: 'workspace_overview',
          i18nKey: 'route.workspace_overview',
          roles: ['R_USER'],
          hideInMenu: true,
          icon: 'mdi:view-dashboard-outline',
          order: 1
        }
      },
      {
        name: 'workspace_profile',
        path: '/workspace/profile',
        component: 'view.workspace_profile',
        meta: {
          title: 'workspace_profile',
          i18nKey: 'route.workspace_profile',
          roles: ['R_USER'],
          hideInMenu: true,
          icon: 'mdi:card-account-details-outline',
          order: 5
        }
      },
      {
        name: 'workspace_security',
        path: '/workspace/security',
        component: 'view.workspace_security',
        meta: {
          title: 'workspace_security',
          i18nKey: 'route.workspace_security',
          roles: ['R_USER'],
          hideInMenu: true,
          icon: 'mdi:shield-account',
          order: 4
        }
      },
      {
        name: 'workspace_sessions',
        path: '/workspace/sessions',
        component: 'view.workspace_sessions',
        meta: {
          title: 'workspace_sessions',
          i18nKey: 'route.workspace_sessions',
          roles: ['R_USER'],
          hideInMenu: true,
          icon: 'mdi:devices',
          order: 3
        }
      }
    ]
  }
];
