/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base',
    meta: {
      title: 'audit',
      icon: 'ph:warning-bold',
      i18nKey: 'route.audit',
      order: 4,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'audit_baselogs',
        path: '/audit/baselogs',
        component: 'view.audit_baselogs',
        meta: {
          title: 'audit_baselogs',
          i18nKey: 'route.audit_baselogs',
          icon: 'hugeicons:files-01'
        }
      },
      {
        name: 'audit_filetransferlogs',
        path: '/audit/filetransferlogs',
        component: 'view.audit_filetransferlogs',
        meta: {
          title: 'audit_filetransferlogs',
          i18nKey: 'route.audit_filetransferlogs',
          icon: 'solar:square-transfer-horizontal-linear'
        }
      },
      {
        name: 'audit_loginlogs',
        path: '/audit/loginlogs',
        component: 'view.audit_loginlogs',
        meta: {
          title: 'audit_loginlogs',
          i18nKey: 'route.audit_loginlogs',
          icon: 'ic:baseline-login'
        }
      }
    ]
  },
  {
    name: 'devices',
    path: '/devices',
    component: 'layout.base$view.devices',
    meta: {
      title: 'devices',
      i18nKey: 'route.devices',
      icon: 'mdi:desktop-classic',
      order: 6,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'my-devices',
    path: '/my-devices',
    component: 'layout.base',
    meta: {
      title: 'my-devices',
      i18nKey: 'route.my-devices',
      icon: 'mdi:book-open-variant',
      order: 3
    },
    children: [
      {
        name: 'my-devices_manage',
        path: '/my-devices/manage',
        component: 'view.my-devices_manage',
        meta: {
          title: 'my-devices_manage',
          i18nKey: 'route.my-devices_manage',
          icon: 'mdi:book-cog'
        }
      },
      {
        name: 'my-devices_peers',
        path: '/my-devices/peers',
        component: 'view.my-devices_peers',
        meta: {
          title: 'my-devices_peers',
          i18nKey: 'route.my-devices_peers',
          icon: 'mdi:account-multiple'
        }
      },
      {
        name: 'my-devices_tags',
        path: '/my-devices/tags',
        component: 'view.my-devices_tags',
        meta: {
          title: 'my-devices_tags',
          i18nKey: 'route.my-devices_tags',
          icon: 'mdi:tag-multiple'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'hugeicons:system-update-01',
      order: 5,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'system_mail',
        path: '/system/mail',
        meta: {
          title: 'system_mail',
          i18nKey: 'route.system_mail'
        },
        children: [
          {
            name: 'system_mail_logs',
            path: '/system/mail/logs',
            component: 'view.system_mail_logs',
            meta: {
              title: 'system_mail_logs',
              i18nKey: 'route.system_mail_logs',
              icon: 'icon-park-outline:upload-logs'
            }
          },
          {
            name: 'system_mail_template',
            path: '/system/mail/template',
            component: 'view.system_mail_template',
            meta: {
              title: 'system_mail_template',
              i18nKey: 'route.system_mail_template',
              icon: 'fluent:mail-template-16-regular'
            }
          }
        ]
      },
      {
        name: 'system_oauth',
        path: '/system/oauth',
        component: 'view.system_oauth',
        meta: {
          title: 'system_oauth',
          i18nKey: 'route.system_oauth',
          icon: 'mdi:shield-lock'
        }
      },
      {
        name: 'system_server',
        path: '/system/server',
        component: 'view.system_server',
        meta: {
          title: 'system_server',
          i18nKey: 'route.system_server',
          icon: 'mdi:server-network'
        }
      },
      {
        name: 'system_tokens',
        path: '/system/tokens',
        component: 'view.system_tokens',
        meta: {
          title: 'system_tokens',
          i18nKey: 'route.system_tokens',
          icon: 'mdi:key-*variant'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      icon: 'majesticons:users-line',
      i18nKey: 'route.user',
      order: 2,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: 'user_list',
          i18nKey: 'route.user_list',
          requiresAuth: true,
          icon: 'gravity-ui:person'
        }
      },
      {
        name: 'user_sessions',
        path: '/user/sessions',
        component: 'view.user_sessions',
        meta: {
          title: 'user_sessions',
          i18nKey: 'route.user_sessions',
          requiresAuth: true,
          icon: 'carbon:mobile-session'
        }
      }
    ]
  }
];
